// Auto-generated by cache-remote-images.mjs
// Mapping of original remote URL to local optimized asset hash + widths
export const REMOTE_IMAGE_MANIFEST: Record<string, { hash: string; widths: number[]; formats: string[] }> = {
  "https://m.media-amazon.com/images/I/71CgZTnYGkL._AC_SY879_.jpg": {
    "hash": "1c0cf16fc554",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/81mnIaDr0PL._AC_SL1500_.jpg": {
    "hash": "e09727cf390e",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/718TaPAvL+L._AC_SL1500_.jpg": {
    "hash": "646894152731",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/7162k36ybFL._AC_SX679_.jpg": {
    "hash": "9e491bebc13a",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/61rHyZ0u-4L._AC_SX679_.jpg": {
    "hash": "56f5a4d56e8c",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71xXJMcUcbL._AC_SX679_.jpg": {
    "hash": "6ca041b86b31",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/61dWe19AxkL._AC_SX425_.jpg": {
    "hash": "be7607cbb051",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/61KUMakLYdL._AC_SX425_.jpg": {
    "hash": "495919d096e9",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/616crE2-xeL._AC_SX425_.jpg": {
    "hash": "e73a31d696a9",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/6103RpMQKcL._AC_SL1500_.jpg": {
    "hash": "6181a53f2888",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71SLDsKoQKL._AC_SY300_SX300_QL70_FMwebp_.jpg": {
    "hash": "75702ec84514",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/51TOhmDTg6L._AC_SL1000_.jpg": {
    "hash": "769f36d870b2",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71l-qL3KXRL._AC_SX425_.jpg": {
    "hash": "aa7414cad5f1",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/61A-zRQCJiL._AC_SY679_.jpg": {
    "hash": "eda24b40a6cb",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/61Qgi0HwXFL._AC_SX425_.jpg": {
    "hash": "20fb7897f9cb",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71-nKyJz+jL._AC_SX679_.jpg": {
    "hash": "c93c9e7897ff",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/61hHSBp0BBL._AC_SX679_.jpg": {
    "hash": "8f1b7cd4bd46",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/61eWi3sq8+L._AC_SY879_.jpg": {
    "hash": "080d78792677",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/810wCtCHD-L._AC_SX425_.jpg": {
    "hash": "c0e4c9fd354d",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71x7tiVE9eL._AC_SX425_.jpg": {
    "hash": "3e0e8256c9bb",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/thr/thr75703/g/85.jpg": {
    "hash": "b975bb4b2560",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71KrZx9cRTL._AC_SY741_.jpg": {
    "hash": "984755d41f2c",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/61MUlupX8WL._AC_SY606_.jpg": {
    "hash": "74d99fef8279",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71qVP5S-iWL._AC_SX425_.jpg": {
    "hash": "c9331cf56ab7",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/716IoQSJ4YL._AC_SX425_.jpg": {
    "hash": "74d55a2ad437",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/61QF4SbSxfL._AC_SX425_.jpg": {
    "hash": "13e5cc7b6056",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/61a4cdr-hWL._AC_SX425_.jpg": {
    "hash": "03a220973b0b",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/713hbdyLbSL._AC_SX425_.jpg": {
    "hash": "5a035b347bf3",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71owMb26MnL._AC_SY300_SX300_QL70_FMwebp_.jpg": {
    "hash": "9ce31579c576",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71uUmLdFh9L._AC_SX425_.jpg": {
    "hash": "830b05a18399",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71kQn9I4TbL._AC_SX425_.jpg": {
    "hash": "549730985361",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71j+fpD+9NL._AC_SX425_.jpg": {
    "hash": "bc060f78399d",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71uiX68Q5nL._AC_SX425_.jpg": {
    "hash": "c6a95ca98437",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/61uOWrsJQQL._AC_SX679_.jpg": {
    "hash": "faf2e06b018e",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/81I9DWbPCyL._AC_SX679_.jpg": {
    "hash": "5b622405ae5b",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71-0onWFI2L._AC_SY450_.jpg": {
    "hash": "dbfe7430e12f",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71+R-I6pUjL._AC_SL1500_.jpg": {
    "hash": "e3bd3e15a30a",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01058/g/87.jpg": {
    "hash": "24e98fe71496",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/clf/clf05104/g/31.jpg": {
    "hash": "fbbaf743a609",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/81+Weot4A1L._AC_SL1500_.jpg": {
    "hash": "f0bdee94ebd3",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/swv/swv06048/g/48.jpg": {
    "hash": "e0ab758cd590",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/thr/thr66001/g/47.jpg": {
    "hash": "a9d0f16fad6f",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71Z59kI-WeL._AC_SL1500_.jpg": {
    "hash": "2954c3fa9994",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71sgfP-kcnL._AC_SL1500_.jpg": {
    "hash": "315c630e3b03",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/rul/rul00442/y/40.jpg": {
    "hash": "65cac981593b",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/714UFxWRUFL._AC_SL1500_.jpg": {
    "hash": "49dac4d0104d",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn00940/y/184.jpg": {
    "hash": "e52749b4a76f",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ndm/ndm02754/y/37.jpg": {
    "hash": "69f7c30c8033",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://m.media-amazon.com/images/I/71f+UBXh2vL._AC_SL1500_.jpg": {
    "hash": "b1f4a8591ff7",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01064/y/134.jpg": {
    "hash": "75f4412b58af",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/spn/spn02345/y/9.jpg": {
    "hash": "3f20ff4d3755",
    "widths": [
      240,
      360,
      480
    ],
    "formats": [
      "avif",
      "webp"
    ]
  }
};
