// Auto-generated by cache-remote-images.mjs
// Mapping of original remote URL to local optimized asset hash + widths
export const REMOTE_IMAGE_MANIFEST: Record<string, { hash: string; widths: number[]; formats: string[] }> = {
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/thr/thr75703/g/85.jpg": {
    "hash": "b975bb4b2560",
    "widths": [
      240,
      360,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01058/g/87.jpg": {
    "hash": "24e98fe71496",
    "widths": [
      240,
      360,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/clf/clf05104/g/31.jpg": {
    "hash": "fbbaf743a609",
    "widths": [
      240,
      360,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/swv/swv06048/g/48.jpg": {
    "hash": "e0ab758cd590",
    "widths": [
      240,
      360,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/thr/thr66001/g/47.jpg": {
    "hash": "a9d0f16fad6f",
    "widths": [
      240,
      360,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/rul/rul00442/y/40.jpg": {
    "hash": "65cac981593b",
    "widths": [
      240,
      360,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn00940/y/184.jpg": {
    "hash": "e52749b4a76f",
    "widths": [
      240,
      360,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ndm/ndm02754/y/37.jpg": {
    "hash": "69f7c30c8033",
    "widths": [
      240,
      360,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01064/y/134.jpg": {
    "hash": "75f4412b58af",
    "widths": [
      240,
      360,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  },
  "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/spn/spn02345/y/9.jpg": {
    "hash": "3f20ff4d3755",
    "widths": [
      240,
      360,
      480,
      640
    ],
    "formats": [
      "avif",
      "webp"
    ]
  }
};
