// AUTO-GENERATED from database - 2025-12-01
// Run: node scripts/sync-autolink-from-db.mjs

const GLOSSARY_TERMS: GlossaryTerm[] = [
  { key: "absorption", terms: ["Absorption", "absorption", "absorptions"] },
  { key: "acetate", terms: ["Acetate", "acetate", "C2:0", "acetates"] },
  { key: "adaptogen", terms: ["Adaptogen", "adaptogen", "adaptogens"] },
  { key: "adverseeffects", terms: ["Adverse Effects", "adverse effects", "adverse-effects"] },
  { key: "akkermansia", terms: ["Akkermansia muciniphila", "akkermansia muciniphila", "akkermansia-muciniphila"] },
  { key: "ala", terms: ["ALA (Alpha-Linolenic Acid)", "ala (alpha-linolenic acid)", "ALA", "ala-(alpha-linolenic-acid)"] },
  { key: "aminoacids", terms: ["Amino Acids", "amino acids", "amino-acids"] },
  { key: "anabolicresistance", terms: ["Anabolic Resistance", "anabolic resistance", "anabolic-resistance"] },
  { key: "anecdotalevidence", terms: ["Anecdotal Evidence", "anecdotal evidence", "anecdotal-evidence"] },
  { key: "anemia", terms: ["Anemia", "anemia", "anemias"] },
  { key: "antioxidant", terms: ["Antioxidant", "antioxidant", "antioxidants"] },
  { key: "arachidonicacid", terms: ["Arachidonic Acid (AA)", "arachidonic acid (aa)", "AA", "arachidonic-acid-(aa)"] },
  { key: "arr", terms: ["Absolute Risk Reduction", "absolute risk reduction", "ARR", "absolute-risk-reduction"] },
  { key: "atherosclerosis", terms: ["Atherosclerosis", "atherosclerosis"] },
  { key: "atp", terms: ["ATP (Adenosine Triphosphate)", "atp (adenosine triphosphate)", "ATP", "atp-(adenosine-triphosphate)"] },
  { key: "bacteroides", terms: ["Bacteroides", "bacteroides"] },
  { key: "betacarotene", terms: ["Beta-Carotene", "beta-carotene", "β-Carotene", "beta-carotenes"] },
  { key: "bifidobacterium", terms: ["Bifidobacterium", "bifidobacterium", "bifidobacteriums"] },
  { key: "bioavailability", terms: ["Bioavailability", "bioavailability", "bioavailabilitys"] },
  { key: "biomarker", terms: ["Biomarker", "biomarker", "biomarkers"] },
  { key: "bloodglucose", terms: ["Blood Glucose", "blood glucose", "blood-glucose"] },
  { key: "bloodpressure", terms: ["Blood Pressure", "blood pressure", "blood-pressure"] },
  { key: "bmi", terms: ["BMI", "bmi", "bmis"] },
  { key: "bonedensity", terms: ["Bone Density", "bone density", "BMD", "bone-density"] },
  { key: "butyrate", terms: ["Butyrate", "butyrate", "C4:0", "butyrates"] },
  { key: "calciumcarbonate", terms: ["Calcium Carbonate", "calcium carbonate", "CaCO₃", "calcium-carbonate"] },
  { key: "calciumcitrate", terms: ["Calcium Citrate", "calcium citrate", "calcium-citrate"] },
  { key: "cardiovascular", terms: ["Cardiovascular", "cardiovascular", "cardiovasculars"] },
  { key: "carotenoids", terms: ["Carotenoids", "carotenoids"] },
  { key: "catalase", terms: ["Catalase", "catalase", "catalases"] },
  { key: "chelated", terms: ["Chelated", "chelated", "chelateds"] },
  { key: "chylomicrons", terms: ["Chylomicrons", "chylomicrons"] },
  { key: "ci", terms: ["Confidence Interval", "confidence interval", "CI", "confidence-interval"] },
  { key: "clinicalsignificance", terms: ["Clinical Significance", "clinical significance", "clinical-significance"] },
  { key: "coenzymeq10", terms: ["Coenzyme Q10", "coenzyme q10", "CoQ10", "ubiquinone", "coenzyme-q10"] },
  { key: "cognitivefunction", terms: ["Cognitive Function", "cognitive function", "cognitive-function"] },
  { key: "cohortstudy", terms: ["Cohort Study", "cohort study", "cohort-study"] },
  { key: "collagen", terms: ["Collagen", "collagen", "collagens"] },
  { key: "colonocytes", terms: ["Colonocytes", "colonocytes"] },
  { key: "contraindications", terms: ["Contraindications", "contraindications"] },
  { key: "cortisol", terms: ["Cortisol", "cortisol", "cortisols"] },
  { key: "creatinekinase", terms: ["Creatine Kinase", "creatine kinase", "CK", "creatine-kinase"] },
  { key: "crosssectionalstudy", terms: ["Cross-Sectional Study", "cross-sectional study", "cross-sectional-study"] },
  { key: "crp", terms: ["CRP (C-Reactive Protein)", "crp (c-reactive protein)", "CRP", "crp-(c-reactive-protein)"] },
  { key: "cytokines", terms: ["Cytokines", "cytokines"] },
  { key: "deficiency", terms: ["Deficiency", "deficiency", "deficiencys"] },
  { key: "dha", terms: ["DHA (Docosahexaenoic Acid)", "dha (docosahexaenoic acid)", "DHA", "dha-(docosahexaenoic-acid)"] },
  { key: "diastolic", terms: ["Diastolic Blood Pressure", "diastolic blood pressure", "diastolic-blood-pressure"] },
  { key: "doms", terms: ["DOMS (Delayed Onset Muscle Soreness)", "doms (delayed onset muscle soreness)", "DOMS", "doms-(delayed-onset-muscle-soreness)"] },
  { key: "dosedependent", terms: ["Dose-Dependent", "dose-dependent", "dose-dependents"] },
  { key: "doubleblinded", terms: ["Double Blinded", "double blinded", "double-blinded"] },
  { key: "druginteractions", terms: ["Drug Interactions", "drug interactions", "drug-interactions"] },
  { key: "dysbiosis", terms: ["Dysbiosis", "dysbiosis"] },
  { key: "effectsize", terms: ["Effect Size", "effect size", "effect-size"] },
  { key: "efficacy", terms: ["Efficacy", "efficacy", "efficacys"] },
  { key: "eicosanoids", terms: ["Eicosanoids", "eicosanoids"] },
  { key: "eightohdg", terms: ["8-OHdG", "8-ohdg", "8-oxo-dG", "8-ohdgs"] },
  { key: "electrolytes", terms: ["Electrolytes", "electrolytes"] },
  { key: "empiricalevidence", terms: ["Empirical Evidence", "empirical evidence", "empirical-evidence"] },
  { key: "endothelium", terms: ["Endothelium", "endothelium", "endotheliums"] },
  { key: "enterocytes", terms: ["Enterocytes", "enterocytes"] },
  { key: "epa", terms: ["EPA (Eicosapentaenoic Acid)", "epa (eicosapentaenoic acid)", "EPA", "epa-(eicosapentaenoic-acid)"] },
  { key: "esr", terms: ["ESR (Erythrocyte Sedimentation Rate)", "esr (erythrocyte sedimentation rate)", "ESR", "esr-(erythrocyte-sedimentation-rate)"] },
  { key: "essentialaminoacids", terms: ["Essential Amino Acids", "essential amino acids", "EAAs", "essential-amino-acids"] },
  { key: "faecalibacterium", terms: ["Faecalibacterium prausnitzii", "faecalibacterium prausnitzii", "faecalibacterium-prausnitzii"] },
  { key: "ferriciron", terms: ["Ferric Iron", "ferric iron", "ferric-iron"] },
  { key: "ferrousiron", terms: ["Ferrous Iron", "ferrous iron", "ferrous-iron"] },
  { key: "fibrinogen", terms: ["Fibrinogen", "fibrinogen", "fibrinogens"] },
  { key: "flavonoids", terms: ["Flavonoids", "flavonoids"] },
  { key: "fmd", terms: ["Flow-Mediated Dilation", "flow-mediated dilation", "FMD", "flow-mediated-dilation"] },
  { key: "fodmap", terms: ["FODMAP", "fodmap", "fodmaps"] },
  { key: "folicacid", terms: ["Folic Acid", "folic acid", "folic-acid"] },
  { key: "fos", terms: ["Fructooligosaccharides (FOS)", "fructooligosaccharides (fos)", "FOS", "fructooligosaccharides-(fos)"] },
  { key: "freeradicals", terms: ["Free Radicals", "free radicals", "free-radicals"] },
  { key: "glp1", terms: ["Glucagon-Like Peptide-1", "glucagon-like peptide-1", "GLP-1", "glucagon-like-peptide-1"] },
  { key: "glucagon", terms: ["Glucagon", "glucagon", "glucagons"] },
  { key: "glucosemetabolism", terms: ["Glucose Metabolism", "glucose metabolism", "glucose-metabolism"] },
  { key: "glutathione", terms: ["Glutathione", "glutathione", "GSH", "glutathiones"] },
  { key: "glutathioneperoxidase", terms: ["Glutathione Peroxidase", "glutathione peroxidase", "GPx", "glutathione-peroxidase"] },
  { key: "glycemiccontrol", terms: ["Glycemic Control", "glycemic control", "glycemic-control"] },
  { key: "glycine", terms: ["Glycine", "glycine", "Gly", "glycines"] },
  { key: "gos", terms: ["Galacto-oligosaccharides", "galacto-oligosaccharides", "GOS"] },
  { key: "grade", terms: ["GRADE (Grading of Recommendations Assessment, Development and Evaluation)", "grade (grading of recommendations assessment, development and evaluation)", "GRADE", "grade-(grading-of-recommendations-assessment,-development-and-evaluation)"] },
  { key: "gutmicrobiome", terms: ["Gut Microbiome", "gut microbiome", "gut-microbiome"] },
  { key: "halflife", terms: ["Half-Life", "half-life", "half-lifes"] },
  { key: "hba1c", terms: ["HbA1c (Hemoglobin A1c)", "hba1c (hemoglobin a1c)", "HbA1c", "A1C", "hba1c-(hemoglobin-a1c)"] },
  { key: "hdlcholesterol", terms: ["HDL Cholesterol (High-Density Lipoprotein)", "hdl cholesterol (high-density lipoprotein)", "HDL", "HDL-C", "hdl-cholesterol-(high-density-lipoprotein)"] },
  { key: "hedgesg", terms: ["Hedges' g", "hedges' g", "hedges'-g"] },
  { key: "hemeiron", terms: ["Heme Iron", "heme iron", "None", "heme-iron"] },
  { key: "hemoglobin", terms: ["Hemoglobin", "hemoglobin", "Hb", "hemoglobins"] },
  { key: "hepaticencephalopathy", terms: ["Hepatic Encephalopathy", "hepatic encephalopathy", "hepatic-encephalopathy"] },
  { key: "homair", terms: ["HOMA-IR", "homa-ir", "homa-irs"] },
  { key: "homocysteine", terms: ["Homocysteine", "homocysteine", "homocysteines"] },
  { key: "hydrolyzed", terms: ["Hydrolyzed", "hydrolyzed", "hydrolyzeds"] },
  { key: "hydroxyproline", terms: ["Hydroxyproline", "hydroxyproline", "hydroxyprolines"] },
  { key: "hyperglycemia", terms: ["Hyperglycemia", "hyperglycemia", "hyperglycemias"] },
  { key: "hypertensive", terms: ["Hypertensive", "hypertensive", "hypertensives"] },
  { key: "ibs", terms: ["Irritable Bowel Syndrome", "irritable bowel syndrome", "IBS", "irritable-bowel-syndrome"] },
  { key: "il1", terms: ["Interleukin-1", "interleukin-1", "IL-1", "interleukin-1s"] },
  { key: "il6", terms: ["Interleukin-6", "interleukin-6", "IL-6", "interleukin-6s"] },
  { key: "immunesystem", terms: ["Immune System", "immune system", "immune-system"] },
  { key: "inflammation", terms: ["Inflammation", "inflammation", "inflammations"] },
  { key: "inflammatoryboweldisease", terms: ["Inflammatory Bowel Disease", "inflammatory bowel disease", "IBD", "inflammatory-bowel-disease"] },
  { key: "insulin", terms: ["Insulin", "insulin", "insulins"] },
  { key: "insulinresistance", terms: ["Insulin Resistance", "insulin resistance", "insulin-resistance"] },
  { key: "inulintypefructans", terms: ["Inulin-type Fructans", "inulin-type fructans", "inulin-type-fructans"] },
  { key: "isoleucine", terms: ["Isoleucine", "isoleucine", "Ile", "isoleucines"] },
  { key: "jointhealth", terms: ["Joint Health", "joint health", "joint-health"] },
  { key: "lactobacillus", terms: ["Lactobacillus", "lactobacillus"] },
  { key: "ldlcholesterol", terms: ["LDL Cholesterol (Low-Density Lipoprotein)", "ldl cholesterol (low-density lipoprotein)", "LDL", "LDL-C", "ldl-cholesterol-(low-density-lipoprotein)"] },
  { key: "leucine", terms: ["Leucine", "leucine", "Leu", "leucines"] },
  { key: "lipidperoxidation", terms: ["Lipid Peroxidation", "lipid peroxidation", "None", "lipid-peroxidation"] },
  { key: "loadingphase", terms: ["Loading Phase", "loading phase", "loading-phase"] },
  { key: "lycopene", terms: ["Lycopene", "lycopene", "lycopenes"] },
  { key: "macromineral", terms: ["Macromineral", "macromineral", "macrominerals"] },
  { key: "magnesiumcitrate", terms: ["Magnesium Citrate", "magnesium citrate", "magnesium-citrate"] },
  { key: "magnesiumoxide", terms: ["Magnesium Oxide", "magnesium oxide", "MgO", "magnesium-oxide"] },
  { key: "maintenancedose", terms: ["Maintenance Dose", "maintenance dose", "maintenance-dose"] },
  { key: "mda", terms: ["Malondialdehyde", "malondialdehyde", "MDA", "malondialdehydes"] },
  { key: "metaanalysis", terms: ["Meta-Analysis", "meta-analysis"] },
  { key: "metabolicsyndrome", terms: ["Metabolic Syndrome", "metabolic syndrome", "metabolic-syndrome"] },
  { key: "metabolism", terms: ["Metabolism", "metabolism", "metabolisms"] },
  { key: "methylcobalamin", terms: ["Methylcobalamin", "methylcobalamin", "MeCbl", "methylcobalamins"] },
  { key: "methylfolate", terms: ["Methylfolate", "methylfolate", "5-MTHF", "methylfolates"] },
  { key: "micronized", terms: ["Micronized", "micronized", "micronizeds"] },
  { key: "mineral", terms: ["Mineral", "mineral", "minerals"] },
  { key: "mitochondria", terms: ["Mitochondria", "mitochondria", "mitochondrias"] },
  { key: "mtor", terms: ["mTOR", "mtor", "mtors"] },
  { key: "muscleproteinsynthesis", terms: ["Muscle Protein Synthesis", "muscle protein synthesis", "MPS", "muscle-protein-synthesis"] },
  { key: "myoglobin", terms: ["Myoglobin", "myoglobin", "myoglobins"] },
  { key: "neurotransmitter", terms: ["Neurotransmitter", "neurotransmitter", "neurotransmitters"] },
  { key: "nfkb", terms: ["NF-κB", "nf-κb", "nf-κbs"] },
  { key: "nitricoxide", terms: ["Nitric Oxide (NO)", "nitric oxide (no)", "NO", "nitric-oxide-(no)"] },
  { key: "nonhemeiron", terms: ["Non-Heme Iron", "non-heme iron", "None", "non-heme-iron"] },
  { key: "normotensive", terms: ["Normotensive", "normotensive", "normotensives"] },
  { key: "nrf2", terms: ["Nrf2", "nrf2", "nrf2s"] },
  { key: "observationalstudy", terms: ["Observational Study", "observational study", "observational-study"] },
  { key: "omega3", terms: ["Omega-3 Fatty Acids", "omega-3 fatty acids", "omega-3-fatty-acids"] },
  { key: "or", terms: ["Odds Ratio", "odds ratio", "OR", "odds-ratio"] },
  { key: "osteomalach", terms: ["Osteomalacia", "osteomalacia", "osteomalacias"] },
  { key: "osteoporosis", terms: ["Osteoporosis", "osteoporosis"] },
  { key: "oxalates", terms: ["Oxalates", "oxalates"] },
  { key: "oxidativedamage", terms: ["Oxidative Damage", "oxidative damage", "oxidative-damage"] },
  { key: "oxidativestress", terms: ["Oxidative Stress", "oxidative stress", "oxidative-stress"] },
  { key: "oxidizedldl", terms: ["Oxidized LDL", "oxidized ldl", "oxLDL", "oxidized-ldl"] },
  { key: "pancreatitis", terms: ["Pancreatitis", "pancreatitis"] },
  { key: "pedro", terms: ["PEDro Scale", "pedro scale", "PEDro", "pedro-scale"] },
  { key: "peerreviewed", terms: ["Peer-reviewed", "peer-reviewed", "peer-revieweds"] },
  { key: "pharmacokinetics", terms: ["Pharmacokinetics", "pharmacokinetics"] },
  { key: "phosphocreatine", terms: ["Phosphocreatine", "phosphocreatine", "PCr", "phosphocreatines"] },
  { key: "phytates", terms: ["Phytates", "phytates", "IP6"] },
  { key: "placebo", terms: ["Placebo", "placebo", "placebos"] },
  { key: "plasma", terms: ["Plasma", "plasma", "plasmas"] },
  { key: "pms", terms: ["PMS (Premenstrual Syndrome)", "pms (premenstrual syndrome)", "PMS", "pms-(premenstrual-syndrome)"] },
  { key: "polyphenols", terms: ["Polyphenols", "polyphenols"] },
  { key: "prediabetes", terms: ["Prediabetes", "prediabetes"] },
  { key: "preeclampsia", terms: ["Pre-eclampsia", "pre-eclampsia", "pre-eclampsias"] },
  { key: "proline", terms: ["Proline", "proline", "Pro", "prolines"] },
  { key: "propionate", terms: ["Propionate", "propionate", "C3:0", "propionates"] },
  { key: "protein", terms: ["Protein", "protein", "proteins"] },
  { key: "proteinsynthesis", terms: ["Protein Synthesis", "protein synthesis", "protein-synthesis"] },
  { key: "pyy", terms: ["Peptide YY", "peptide yy", "PYY", "peptide-yy"] },
  { key: "rct", terms: ["Randomized Controlled Trial", "randomized controlled trial", "RCT", "randomized-controlled-trial"] },
  { key: "resolvins", terms: ["Resolvins", "resolvins", "RvE"] },
  { key: "resveratrol", terms: ["Resveratrol", "resveratrol", "resveratrols"] },
  { key: "rheumatoidarthritis", terms: ["Rheumatoid Arthritis", "rheumatoid arthritis", "RA", "rheumatoid-arthritis"] },
  { key: "rickets", terms: ["Rickets", "rickets"] },
  { key: "rr", terms: ["Risk Ratio", "risk ratio", "RR", "risk-ratio"] },
  { key: "satiety", terms: ["Satiety", "satiety", "satietys"] },
  { key: "saturation", terms: ["Saturation", "saturation", "saturations"] },
  { key: "scfa", terms: ["SCFA (Short-Chain Fatty Acids)", "scfa (short-chain fatty acids)", "SCFA", "SCFAs", "scfa-(short-chain-fatty-acids)"] },
  { key: "serum", terms: ["Serum", "serum", "serums"] },
  { key: "serum25ohd", terms: ["Serum 25-hydroxyvitamin D / 25(OH)D", "serum 25-hydroxyvitamin d / 25(oh)d", "serum-25-hydroxyvitamin-d-/-25(oh)d"] },
  { key: "sibo", terms: ["Small Intestinal Bacterial Overgrowth", "small intestinal bacterial overgrowth", "SIBO", "small-intestinal-bacterial-overgrowth"] },
  { key: "singleblinded", terms: ["Single Blinded", "single blinded", "single-blinded"] },
  { key: "sleepquality", terms: ["Sleep Quality", "sleep quality", "sleep-quality"] },
  { key: "smd", terms: ["Standardized Mean Difference", "standardized mean difference", "SMD", "standardized-mean-difference"] },
  { key: "standardizedextract", terms: ["Standardized Extract", "standardized extract", "standardized-extract"] },
  { key: "statisticalsignificance", terms: ["Statistical Significance", "statistical significance", "statistical-significance"] },
  { key: "subgroupanalysis", terms: ["Subgroup Analysis", "subgroup analysis", "subgroup-analysis"] },
  { key: "sublingual", terms: ["Sublingual Administration", "sublingual administration", "sublingual-administration"] },
  { key: "superoxidedismutase", terms: ["Superoxide Dismutase", "superoxide dismutase", "SOD", "superoxide-dismutase"] },
  { key: "synergisticeffect", terms: ["Synergistic Effect", "synergistic effect", "synergistic-effect"] },
  { key: "systematicreview", terms: ["Systematic Review", "systematic review", "systematic-review"] },
  { key: "systolic", terms: ["Systolic Blood Pressure", "systolic blood pressure", "systolic-blood-pressure"] },
  { key: "tac", terms: ["Total Antioxidant Capacity", "total antioxidant capacity", "TAC", "total-antioxidant-capacity"] },
  { key: "therapeuticdose", terms: ["Therapeutic Dose", "therapeutic dose", "therapeutic-dose"] },
  { key: "thirdpartytesting", terms: ["Third-Party Testing", "third-party testing", "third-party-testing"] },
  { key: "thyroidfunction", terms: ["Thyroid Function", "thyroid function", "thyroid-function"] },
  { key: "tnfalpha", terms: ["Tumor Necrosis Factor-Alpha", "tumor necrosis factor-alpha", "TNF-α", "tumor-necrosis-factor-alpha"] },
  { key: "tolerableupperintakelevel", terms: ["Tolerable Upper Intake Level", "tolerable upper intake level", "UL", "tolerable-upper-intake-level"] },
  { key: "triglycerides", terms: ["Triglycerides", "triglycerides"] },
  { key: "ulcerativecolitis", terms: ["Ulcerative Colitis", "ulcerative colitis", "UC", "ulcerative-colitis"] },
  { key: "valine", terms: ["Valine", "valine", "Val", "valines"] },
  { key: "vitamindeficiency", terms: ["Vitamin Deficiency", "vitamin deficiency", "vitamin-deficiency"] },
  { key: "vldl", terms: ["VLDL", "vldl", "vldls"] },
  { key: "wmd", terms: ["Weighted Mean Difference", "weighted mean difference", "WMD", "weighted-mean-difference"] },
];
