-- Auto-generated migration: Populate supplement content from product-context-data.ts
-- Generated: 2025-11-29T12:03:54.683Z
-- Total supplements: 18

BEGIN;

-- ===== Ashwagandha (ashwagandha) =====
UPDATE api.supplements SET
  quick_overview = 'An adaptogenic herb traditionally used in Ayurvedic medicine. Modern research supports its role in stress management and promoting a balanced stress response.',
  extended_overview = 'Ashwagandha (Withania somnifera) has been used for over 3,000 years in traditional Ayurvedic medicine, where it is classified as a Rasayana—an herb that promotes longevity and vitality. The name comes from Sanskrit, meaning ''smell of the horse,'' referring both to its distinct aroma and the traditional belief that it imparts the strength and vigor of a horse. Modern scientific research has validated many traditional uses, with clinical trials demonstrating its ability to modulate the body''s stress response through multiple pathways. The root contains bioactive compounds called withanolides, which are believed to be responsible for most of the herb''s therapeutic effects. These compounds have been shown to influence cortisol levels, support healthy neurotransmitter function, and promote overall physiological balance during times of stress.',
  science_snapshot = 'Clinical studies have shown that ashwagandha root extract can significantly reduce cortisol levels and perceived stress scores compared to placebo. Research also suggests potential benefits for sleep quality, cognitive function, and physical performance, though the strength of evidence varies across these applications.',
  key_benefits = ARRAY['Supports healthy cortisol levels','May help with occasional stress','Traditional adaptogenic properties','Supports overall wellbeing','May support healthy sleep patterns','Traditionally used for vitality'],
  ideal_for = ARRAY['Those managing daily stress','People seeking adaptogenic support','Those interested in Ayurvedic herbs','Individuals with demanding lifestyles'],
  timing_tips = ARRAY['Can be taken morning or evening depending on your goals','Taking with food may improve absorption and reduce stomach sensitivity','Consistency matters more than exact timing for adaptogenic benefits','Some prefer evening dosing for sleep support benefits'],
  quality_markers = ARRAY['KSM-66','Sensoril','root extract','withanolide content','standardized extract'],
  safety_considerations = ARRAY['Generally well-tolerated at recommended doses','Consult healthcare provider if pregnant, nursing, or on medications','May interact with thyroid medications or sedatives'],
  what_to_expect_summary = ARRAY['Most users begin noticing subtle changes in stress resilience within the first few weeks of consistent use','Optimal benefits typically develop over 4-8 weeks of daily supplementation','Sleep quality improvements may take longer to manifest, often 6-12 weeks','Individual responses vary based on baseline stress levels and lifestyle factors'],
  typical_dosage_min = 300,
  typical_dosage_max = 600,
  typical_dosage_unit = 'mg',
  form_notes = '{"capsule":"Convenient for consistent daily dosing with standardized extract","powder":"Flexible dosing, can mix into beverages or smoothies","gummy":"Easy to take, often with added flavoring for palatability","liquid":"Fast absorption, adjustable serving sizes for personalization"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Stress Support","timeframe":"4-8 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Sleep Quality","timeframe":"6-12 weeks","intensity":"Low to Moderate"}}'::jsonb,
  synergy_notes = 'Often combined with other adaptogens like rhodiola or holy basil, and pairs well with magnesium for stress and sleep support.'
WHERE slug = 'ashwagandha';

-- ===== BCAAs (bcaas) =====
UPDATE api.supplements SET
  quick_overview = 'Branched-chain amino acids (leucine, isoleucine, valine) are essential nutrients that support muscle protein synthesis. Popular among athletes and fitness enthusiasts.',
  extended_overview = 'BCAAs represent three of the nine essential amino acids that humans must obtain through diet or supplementation, as the body cannot synthesize them independently. Unlike other amino acids that are metabolized primarily in the liver, BCAAs are uniquely metabolized directly in muscle tissue, making them particularly relevant for athletes and those engaged in regular physical training. Leucine, often considered the most important of the three, acts as a key trigger for muscle protein synthesis through its activation of the mTOR pathway—a cellular signaling mechanism that initiates the building of new muscle proteins. Isoleucine plays a role in glucose uptake into cells and energy production during exercise, while valine contributes to muscle metabolism and nitrogen balance. The popularity of BCAA supplements in the fitness community stems from their targeted delivery of these specific amino acids without the caloric load of whole protein sources, making them particularly appealing for those training in fasted states or seeking to minimize caloric intake while supporting muscle preservation.',
  science_snapshot = 'Research on BCAAs has produced mixed results, with some studies showing benefits for reducing muscle soreness and perceived exertion during exercise, while others suggest that adequate total protein intake may diminish the need for isolated BCAA supplementation. The most consistent findings relate to their role in reducing exercise-induced muscle damage markers and supporting recovery in endurance athletes or those training at high volumes.',
  key_benefits = ARRAY['Supports muscle protein synthesis','May reduce exercise-induced fatigue','Essential amino acid supplementation','Popular for workout recovery','May help preserve lean muscle during caloric restriction','Supports endurance during prolonged exercise'],
  ideal_for = ARRAY['Athletes and active individuals','Those doing resistance training','People with higher protein needs','Endurance athletes training at high volumes','Those training in fasted states'],
  timing_tips = ARRAY['Often taken around workouts','Can be consumed throughout the day','Some prefer intra-workout consumption','Pre-workout dosing may help with energy during training'],
  quality_markers = ARRAY['2:1:1 ratio','instantized','fermented','leucine content'],
  safety_considerations = ARRAY['Generally well-tolerated at recommended doses','Those with maple syrup urine disease should avoid BCAA supplements','May affect blood sugar levels; diabetics should monitor accordingly'],
  what_to_expect_summary = ARRAY['Many users notice reduced muscle soreness within the first week or two of consistent use around training','Recovery benefits typically become more apparent after 2-4 weeks of regular supplementation','Effects may be most noticeable during high-volume training phases or caloric restriction','Those already consuming adequate protein may experience less dramatic effects'],
  typical_dosage_min = 5000,
  typical_dosage_max = 10000,
  typical_dosage_unit = 'mg',
  form_notes = '{"powder":"Mix with water, customizable serving size","capsule":"Convenient, no mixing required","tablet":"Portable, precise dosing"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Recovery Support","timeframe":"2-4 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Reduced Muscle Soreness","timeframe":"1-2 weeks","intensity":"Low to Moderate"}}'::jsonb,
  synergy_notes = 'BCAAs are often stacked with other performance supplements like creatine, beta-alanine, or citrulline for comprehensive workout support. They can complement a whey protein regimen for those seeking targeted intra-workout amino acid delivery.'
WHERE slug = 'bcaas';

-- ===== Calcium (calcium) =====
UPDATE api.supplements SET
  quick_overview = 'An essential mineral critical for bone structure and numerous bodily functions. Supplementation is common for those with dietary restrictions or increased needs.',
  extended_overview = 'Calcium stands as the most abundant mineral in the human body, with approximately 99% stored in bones and teeth where it provides structural integrity and serves as a reservoir for maintaining blood calcium levels. Beyond its well-known role in skeletal health, calcium participates in numerous critical physiological processes including muscle contraction, nerve signal transmission, blood clotting, and cellular signaling. The body maintains tight control over blood calcium levels through a complex hormonal system involving parathyroid hormone, calcitonin, and vitamin D, which can mobilize calcium from bones when dietary intake is insufficient. This homeostatic mechanism means that inadequate calcium intake over time can gradually deplete bone mineral density, even while blood calcium levels remain normal. Calcium absorption efficiency varies significantly based on factors including age (declining as we get older), vitamin D status, the form of calcium consumed, and whether it''s taken with food. Understanding these factors helps explain why calcium supplementation strategies often emphasize split dosing and attention to vitamin D status.',
  science_snapshot = 'Clinical research consistently demonstrates calcium''s essential role in bone health, with supplementation shown to slow bone mineral density loss, particularly when combined with adequate vitamin D. Studies suggest benefits are most pronounced in populations with low dietary calcium intake, older adults, and post-menopausal women. Recent research has also examined calcium''s relationship with cardiovascular health, leading to recommendations for obtaining calcium from food sources when possible and not exceeding upper intake limits.',
  key_benefits = ARRAY['Supports bone and teeth health','Essential mineral for many functions','Important during growth periods','Supports muscle function','Plays a role in nerve transmission','Important for blood clotting processes'],
  ideal_for = ARRAY['Those with limited dairy intake','Post-menopausal women','People with increased calcium needs','Vegans and vegetarians','Older adults concerned about bone density','Those with lactose intolerance'],
  timing_tips = ARRAY['Split doses throughout the day for better absorption','Carbonate forms best taken with food','Avoid taking with iron supplements','Take no more than 500-600mg at once for optimal absorption'],
  quality_markers = ARRAY['elemental calcium amount','vitamin D included','third-party tested','USP verified'],
  safety_considerations = ARRAY['Do not exceed upper intake limits (2,500mg/day for most adults)','May interact with certain medications including antibiotics and bisphosphonates','Those with kidney stones should consult healthcare provider before supplementing','Excessive intake may affect absorption of other minerals like iron and zinc'],
  what_to_expect_summary = ARRAY['Calcium supplementation helps meet daily requirements immediately, but bone density changes occur over months to years','Benefits are most measurable in those with previously inadequate intake','Combining with vitamin D significantly enhances calcium utilization','Consistency over time is more important than any single dose for bone health outcomes'],
  typical_dosage_min = 500,
  typical_dosage_max = 1200,
  typical_dosage_unit = 'mg',
  form_notes = '{"citrate":"Well-absorbed, can take with or without food","carbonate":"Higher elemental calcium, best with meals","hydroxyapatite":"Contains additional bone minerals","algae-derived":"Plant-based source option"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Bone Support","timeframe":"12-24 weeks","intensity":"Low to Moderate"},"secondaryOutcome":{"label":"Meeting Daily Requirements","timeframe":"Immediate","intensity":"Moderate"}}'::jsonb,
  synergy_notes = 'Calcium works synergistically with vitamin D, which enhances intestinal calcium absorption. Vitamin K2 is increasingly recognized as an important companion nutrient that helps direct calcium to bones rather than soft tissues. Magnesium also plays a supportive role in calcium metabolism.'
WHERE slug = 'calcium';

-- ===== Casein Protein (casein-protein) =====
UPDATE api.supplements SET
  quick_overview = 'A slow-digesting milk protein that provides sustained amino acid release. Popular as a nighttime protein source among those building or maintaining muscle.',
  extended_overview = 'Casein protein represents approximately 80% of the total protein found in cow''s milk, with the remaining 20% being whey protein. What distinguishes casein from other protein sources is its unique behavior in the digestive system—when exposed to stomach acid, casein forms a gel-like structure that dramatically slows its digestion and absorption. This results in a gradual, sustained release of amino acids into the bloodstream over several hours, rather than the rapid spike seen with fast-digesting proteins like whey. This extended amino acid delivery makes casein particularly valuable during periods when the body might otherwise enter a catabolic state, such as during overnight fasting while sleeping. The protein is rich in all essential amino acids, including a robust profile of branched-chain amino acids, and provides substantial amounts of calcium and phosphorus as additional nutritional benefits. Micellar casein, the native form found in milk, is generally considered superior to caseinate forms because it retains its natural structure and provides the slowest digestion rate.',
  science_snapshot = 'Research supports casein''s role in providing sustained aminoacidemia (elevated blood amino acid levels), with studies showing amino acid release continuing for up to 7 hours post-consumption. Clinical trials have demonstrated casein''s effectiveness for muscle protein synthesis during sleep and its potential superiority over whey for anti-catabolic effects during extended fasting periods. Some studies suggest the combination of whey and casein may provide complementary benefits for muscle building.',
  key_benefits = ARRAY['Slow, sustained protein release','High-quality complete protein','Rich in essential amino acids','Supports muscle maintenance','Anti-catabolic properties during fasting','Good source of calcium and phosphorus'],
  ideal_for = ARRAY['Those seeking sustained protein release','Nighttime protein supplementation','People building lean muscle','Those with long periods between meals','Individuals focused on muscle preservation during dieting'],
  timing_tips = ARRAY['Often consumed before bed','Can be used between meals','Pairs well with whey for different timing','Consider 30-60 minutes before sleep for overnight amino acid delivery'],
  quality_markers = ARRAY['micellar casein','low lactose','protein per serving','amino acid profile'],
  safety_considerations = ARRAY['Not suitable for those with milk protein allergies','Those with lactose intolerance should choose low-lactose formulations','Generally well-tolerated but may cause digestive discomfort in sensitive individuals'],
  what_to_expect_summary = ARRAY['The sustained amino acid release begins immediately but the muscle-sparing benefits accumulate over weeks of consistent use','Many users notice improved satiety and reduced nighttime hunger when using casein before bed','Muscle preservation benefits are most noticeable during caloric restriction or intense training phases','The thick, creamy texture makes it popular for puddings and recipes beyond just shakes'],
  typical_dosage_min = 20000,
  typical_dosage_max = 40000,
  typical_dosage_unit = 'mg',
  form_notes = '{"micellar":"Natural form, slowest digesting","hydrolyzed":"Partially broken down, faster absorption","powder":"Mix into shakes, puddings, or recipes"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Sustained Amino Acids","timeframe":"1-2 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Muscle Preservation","timeframe":"4-8 weeks","intensity":"Moderate"}}'::jsonb,
  synergy_notes = 'Casein pairs exceptionally well with whey protein—whey for rapid post-workout amino acid delivery and casein for sustained overnight release. Some formulations combine both proteins. Casein also complements creatine supplementation for those focused on muscle building.'
WHERE slug = 'casein-protein';

-- ===== Collagen Peptides (collagen-peptides) =====
UPDATE api.supplements SET
  quick_overview = 'Hydrolyzed collagen provides amino acids that support connective tissues throughout the body. Research suggests benefits for skin, joints, and overall structural support.',
  extended_overview = 'Collagen is the most abundant protein in the human body, forming the structural foundation of skin, bones, tendons, ligaments, and cartilage. As we age, natural collagen production declines—typically beginning in our mid-20s and accelerating after 40—leading to visible signs of aging in skin and potential joint discomfort. Collagen peptides, also known as hydrolyzed collagen, are created by breaking down native collagen into smaller, more easily absorbed fragments through enzymatic hydrolysis. This process yields peptides with molecular weights low enough to be absorbed intact through the intestinal wall and distributed throughout the body. Research suggests these peptides may signal fibroblasts (collagen-producing cells) to increase collagen synthesis, potentially helping to counteract age-related decline. Different collagen types serve different functions: Type I is predominant in skin, bones, and tendons; Type II is found primarily in cartilage; Type III supports skin elasticity and is often found alongside Type I. Most supplements contain Type I and III from bovine or marine sources, while Type II is typically sourced from chicken.',
  science_snapshot = 'Clinical research on collagen peptides has shown promising results, particularly for skin health. Multiple randomized controlled trials demonstrate improvements in skin hydration, elasticity, and wrinkle depth after 8-12 weeks of supplementation. Joint health studies show benefits typically emerging after 3-6 months of consistent use, with some research indicating reduced joint pain in athletes and those with osteoarthritis. The bioavailability of hydrolyzed collagen is well-established, with studies showing peptides appearing in blood within hours of consumption.',
  key_benefits = ARRAY['Supports skin elasticity and hydration','Joint and connective tissue support','Provides specific amino acids','Easily digestible protein source','May support nail and hair strength','Supports gut lining integrity'],
  ideal_for = ARRAY['Those seeking skin support','Active individuals with joint concerns','People over 30 seeking structural support','Athletes looking to support tendons and ligaments','Those recovering from soft tissue injuries'],
  timing_tips = ARRAY['Can be taken any time of day','Many add to morning coffee or smoothies','Consistency is key for results','Taking with vitamin C may enhance collagen synthesis'],
  quality_markers = ARRAY['type I/III collagen','hydrolyzed','grass-fed source','low molecular weight','third-party tested for purity'],
  safety_considerations = ARRAY['Generally very well-tolerated with minimal side effects reported','Those with fish or shellfish allergies should avoid marine collagen','Bovine collagen should be avoided by those with beef allergies','Some products may contain added ingredients; check labels if you have sensitivities'],
  what_to_expect_summary = ARRAY['Skin improvements like hydration and reduced fine lines typically become noticeable after 8-12 weeks of daily use','Joint benefits require longer-term supplementation, often 3-6 months for meaningful effects','Some users notice improvements in nail strength and hair texture as secondary benefits','Results are cumulative—stopping supplementation may lead to gradual return to baseline over time'],
  typical_dosage_min = 5000,
  typical_dosage_max = 15000,
  typical_dosage_unit = 'mg',
  form_notes = '{"powder":"Dissolves in hot or cold liquids","capsule":"No taste, convenient dosing","liquid":"Ready to consume, pre-measured","marine":"Fish-derived, potentially better for skin","bovine":"Cattle-derived, rich in Type I and III"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Skin Hydration","timeframe":"8-12 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Joint Comfort","timeframe":"12-24 weeks","intensity":"Low to Moderate"}}'::jsonb,
  synergy_notes = 'Collagen works synergistically with vitamin C, which is essential for collagen synthesis—many find benefits from taking them together. Hyaluronic acid is another complementary ingredient often combined with collagen for skin hydration. For joint support, collagen can be paired with glucosamine or chondroitin.'
WHERE slug = 'collagen-peptides';

-- ===== Creatine (creatine) =====
UPDATE api.supplements SET
  quick_overview = 'One of the most researched sports supplements available. Creatine monohydrate supports ATP regeneration for high-intensity activities and has emerging cognitive benefits.',
  extended_overview = 'Creatine is a naturally occurring compound found primarily in muscle tissue, where it plays a critical role in rapid energy production during high-intensity, short-duration activities. The body produces creatine from amino acids (arginine, glycine, and methionine) and also obtains it from dietary sources like meat and fish. In muscles, creatine is stored as phosphocreatine, which serves as a readily available phosphate donor to regenerate ATP—the cellular energy currency—during explosive movements like sprinting, jumping, or heavy lifting. Supplementation with creatine monohydrate increases muscle phosphocreatine stores by 20-40%, effectively expanding the body''s capacity for high-intensity work. Beyond athletic performance, creatine has gained attention for potential cognitive benefits, as the brain also relies on phosphocreatine for energy during demanding mental tasks. With over 500 peer-reviewed studies, creatine monohydrate stands as one of the most extensively researched and consistently effective sports supplements available, with an excellent safety profile established over decades of use.',
  science_snapshot = 'Research consistently demonstrates creatine''s effectiveness for increasing strength, power output, and lean muscle mass when combined with resistance training. Meta-analyses show average strength gains of 5-10% beyond training alone. Emerging research supports cognitive benefits, particularly under conditions of sleep deprivation or mental fatigue. Long-term studies confirm safety with no adverse effects on kidney or liver function in healthy individuals. The monohydrate form remains the gold standard, with newer forms showing no superiority despite marketing claims.',
  key_benefits = ARRAY['Supports strength and power output','Well-researched and established','May support cognitive function','Helps with high-intensity exercise','Supports lean muscle mass gains','Excellent safety profile'],
  ideal_for = ARRAY['Strength and power athletes','Those doing high-intensity training','People interested in cognitive support','Older adults seeking to maintain muscle mass','Vegetarians (who have lower baseline creatine stores)'],
  timing_tips = ARRAY['Timing is flexible - consistency matters most','Many take post-workout with carbs','Daily use builds and maintains stores','Loading phase optional but speeds saturation (20g/day for 5-7 days)'],
  quality_markers = ARRAY['Creapure','monohydrate form','no fillers','third-party tested'],
  safety_considerations = ARRAY['Extensive research confirms safety in healthy individuals','Stay well-hydrated when supplementing','Those with pre-existing kidney conditions should consult healthcare provider','No evidence of harm to kidneys or liver in healthy users'],
  what_to_expect_summary = ARRAY['Muscle creatine stores reach saturation within 2-4 weeks of daily supplementation (faster with loading phase)','Strength and power improvements typically become noticeable once stores are saturated','Initial weight gain of 1-3 pounds is common due to increased water retention in muscles—this is normal and indicates the supplement is working','Benefits are maintained with consistent daily use; stopping supplementation leads to gradual return to baseline over 4-6 weeks'],
  typical_dosage_min = 3000,
  typical_dosage_max = 5000,
  typical_dosage_unit = 'mg',
  form_notes = '{"monohydrate":"Gold standard form, most researched","micronized":"Finer particles, mixes better","hcl":"May require smaller doses","powder":"Easy to add to any beverage"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Strength Gains","timeframe":"2-4 weeks","intensity":"Moderate to High"},"secondaryOutcome":{"label":"Power Output","timeframe":"4-8 weeks","intensity":"Moderate"}}'::jsonb,
  synergy_notes = 'Creatine pairs well with carbohydrates, which may enhance muscle uptake through insulin-mediated mechanisms. It''s commonly stacked with protein supplements for comprehensive muscle-building support. Beta-alanine is another popular combination for athletes seeking both power and endurance benefits.'
WHERE slug = 'creatine';

-- ===== Curcumin (curcumin) =====
UPDATE api.supplements SET
  quick_overview = 'The primary active compound in turmeric, curcumin has potent properties but requires enhanced formulations for adequate absorption. Look for bioavailability-enhanced versions.',
  extended_overview = 'Curcumin is the principal bioactive compound found in turmeric (Curcuma longa), the golden-yellow spice that has been used for thousands of years in traditional Ayurvedic and Chinese medicine. While turmeric root contains only about 3% curcumin by weight, this compound is responsible for most of the spice''s researched health benefits. Curcumin belongs to a class of compounds called curcuminoids and exhibits remarkable molecular versatility, interacting with numerous cellular targets involved in inflammation, oxidative stress, and cellular signaling. However, curcumin''s major limitation is its poor bioavailability—when consumed alone, it is poorly absorbed, rapidly metabolized, and quickly eliminated from the body. This challenge has driven the development of various enhanced formulations designed to dramatically improve absorption, including combinations with piperine (black pepper extract), phospholipid complexes (phytosomes), micelle formulations, and nanoparticle technologies. Choosing a bioavailability-enhanced form is essential for achieving meaningful blood levels and therapeutic effects.',
  science_snapshot = 'Clinical research on curcumin has demonstrated benefits for joint comfort, with several trials showing improvements comparable to conventional approaches for mild joint discomfort. Studies also support its role in exercise recovery, showing reduced markers of muscle damage and inflammation following intense physical activity. The antioxidant properties of curcumin have been extensively documented in laboratory studies, though translating these to clinical outcomes requires the enhanced formulations that ensure adequate absorption. Research continues to explore applications in cognitive health, cardiovascular support, and metabolic function.',
  key_benefits = ARRAY['Supports healthy inflammatory response','Antioxidant properties','Traditional Ayurvedic ingredient','Joint and mobility support','May support exercise recovery','Supports cellular health'],
  ideal_for = ARRAY['Those seeking natural joint support','People interested in antioxidant support','Those with active lifestyles','Athletes seeking recovery support','Those interested in traditional herbal approaches'],
  timing_tips = ARRAY['Take with meals containing fat','Piperine formulas best away from medications','Split doses may improve utilization','Consistent daily use provides cumulative benefits'],
  quality_markers = ARRAY['95% curcuminoids','bioavailability enhanced','standardized extract','piperine included'],
  safety_considerations = ARRAY['Generally well-tolerated at recommended doses','Piperine-containing formulas may affect medication metabolism—consult healthcare provider if on medications','High doses may cause digestive discomfort in some individuals','Those with gallbladder issues should consult healthcare provider before use'],
  what_to_expect_summary = ARRAY['Joint comfort benefits typically emerge after 4-8 weeks of consistent supplementation with bioavailable forms','Exercise recovery support may be noticed sooner, often within 2-4 weeks','Effects are cumulative—longer-term use tends to provide more noticeable benefits','Choosing an enhanced bioavailability formulation is crucial for experiencing benefits'],
  typical_dosage_min = 500,
  typical_dosage_max = 2000,
  typical_dosage_unit = 'mg',
  form_notes = '{"with piperine":"Black pepper extract enhances absorption ~2000%","phytosome":"Lipid-bound for improved bioavailability","micelle":"Water-soluble formulation","nanoparticle":"Enhanced absorption technology"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Joint Comfort","timeframe":"4-8 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Recovery Support","timeframe":"2-4 weeks","intensity":"Low to Moderate"}}'::jsonb,
  synergy_notes = 'Curcumin is often combined with other joint-supporting nutrients like glucosamine, chondroitin, or boswellia for comprehensive joint health formulas. Omega-3 fatty acids complement curcumin''s effects on inflammatory balance. Ginger, a botanical relative of turmeric, is sometimes paired with curcumin for synergistic effects.'
WHERE slug = 'curcumin';

-- ===== Iron (iron) =====
UPDATE api.supplements SET
  quick_overview = 'An essential mineral for oxygen transport and energy production. Iron supplementation should be guided by testing, as both deficiency and excess can be problematic.',
  extended_overview = 'Iron is an essential trace mineral that plays a central role in oxygen transport throughout the body. As a key component of hemoglobin in red blood cells and myoglobin in muscle tissue, iron enables these proteins to bind and carry oxygen from the lungs to every cell in the body. Beyond oxygen transport, iron is crucial for energy production within mitochondria, DNA synthesis, and proper immune function. Iron deficiency is the most common nutritional deficiency worldwide, affecting an estimated 2 billion people globally. Symptoms of deficiency include fatigue, weakness, pale skin, shortness of breath, and impaired cognitive function. However, iron is unique among minerals in that the body has no regulated mechanism for excreting excess iron, making overconsumption potentially harmful. This is why iron supplementation should ideally be guided by blood testing (serum ferritin, hemoglobin, and transferrin saturation) rather than taken presumptively. Different forms of supplemental iron vary significantly in absorption and tolerability, with newer chelated forms offering gentler options for those who experience digestive side effects from traditional iron sulfate.',
  science_snapshot = 'Research demonstrates that iron supplementation effectively corrects iron deficiency anemia, with improvements in hemoglobin levels typically seen within 2-4 weeks and full restoration of iron stores taking 3-6 months. Studies show that taking iron with vitamin C significantly enhances absorption, while calcium, coffee, and tea inhibit it. Newer forms like iron bisglycinate show comparable efficacy to iron sulfate with significantly fewer gastrointestinal side effects. Importantly, research also confirms risks of iron overload, reinforcing the importance of testing before and during supplementation.',
  key_benefits = ARRAY['Supports healthy iron levels','Essential for oxygen transport','Supports energy production','Important for blood health','Supports cognitive function','Important for immune health'],
  ideal_for = ARRAY['Those with diagnosed deficiency','Menstruating individuals','Vegetarians and vegans','Pregnant women (under guidance)','Endurance athletes with high iron losses','Those with absorption issues'],
  timing_tips = ARRAY['Take on empty stomach if tolerated','Vitamin C enhances absorption','Avoid taking with calcium or coffee','If GI upset occurs, try taking with a small amount of food'],
  quality_markers = ARRAY['gentle form','elemental iron content','no artificial colors','third-party tested'],
  safety_considerations = ARRAY['Always confirm deficiency with blood tests before supplementing','Iron overload (hemochromatosis) is a serious condition—do not supplement without testing','Keep iron supplements away from children—accidental overdose can be fatal','May cause constipation or dark stools—this is normal but discuss persistent GI issues with healthcare provider'],
  what_to_expect_summary = ARRAY['Energy improvements are often noticed within 4-8 weeks as hemoglobin levels improve','Full restoration of iron stores typically takes 3-6 months of consistent supplementation','Those with severe deficiency may notice more dramatic improvements','Regular blood testing helps monitor progress and determine when to adjust or discontinue supplementation'],
  typical_dosage_min = 18,
  typical_dosage_max = 65,
  typical_dosage_unit = 'mg',
  form_notes = '{"bisglycinate":"Gentle on stomach, well-absorbed","sulfate":"Common form, may cause GI effects","carbonyl":"Highly absorbable, gentle","heme":"Animal-derived, high absorption"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Energy Improvement","timeframe":"4-8 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Iron Level Restoration","timeframe":"8-12 weeks","intensity":"Moderate to High"}}'::jsonb,
  synergy_notes = 'Vitamin C dramatically enhances iron absorption and is often included in iron supplements or recommended to take alongside. Avoid taking iron with calcium supplements, dairy, coffee, or tea as these inhibit absorption. B12 and folate are often supplemented alongside iron for comprehensive blood health support.'
WHERE slug = 'iron';

-- ===== Magnesium (magnesium) =====
UPDATE api.supplements SET
  quick_overview = 'A mineral involved in over 300 enzymatic reactions. Many adults have suboptimal intake, making supplementation beneficial for sleep, muscle function, and overall wellness.',
  extended_overview = 'Magnesium is the fourth most abundant mineral in the human body and serves as a cofactor for over 300 enzymatic reactions, making it essential for virtually every physiological process. These include energy production (ATP synthesis), protein synthesis, muscle and nerve function, blood glucose control, and blood pressure regulation. Despite its importance, magnesium deficiency and insufficiency are remarkably common in modern populations—studies suggest that up to 50% of Americans consume less than the recommended daily amount. This widespread shortfall is attributed to declining soil mineral content, food processing that removes magnesium, and dietary patterns low in magnesium-rich foods like leafy greens, nuts, and whole grains. Subclinical magnesium deficiency can manifest as muscle cramps, sleep difficulties, anxiety, fatigue, and headaches. The form of magnesium supplemented matters significantly: different forms have varying bioavailability and may offer distinct benefits. Magnesium glycinate is prized for its calming effects and gentle absorption, citrate for its good bioavailability (though potential laxative effect), threonate for its unique ability to cross the blood-brain barrier, and malate for energy and muscle support.',
  science_snapshot = 'Clinical research supports magnesium supplementation for multiple applications. Studies demonstrate improvements in sleep quality, particularly with glycinate and citrate forms taken in the evening. Research shows benefits for muscle cramps, exercise performance, and recovery. Magnesium threonate has shown promise in cognitive studies for its ability to increase brain magnesium levels. Meta-analyses confirm modest but consistent blood pressure-lowering effects. The relationship between magnesium and stress/anxiety has been documented in multiple trials, with supplementation showing benefits for those with low baseline intake.',
  key_benefits = ARRAY['Supports muscle relaxation','May improve sleep quality','Supports nerve function','Essential for energy production','May help with stress and tension','Supports cardiovascular health'],
  ideal_for = ARRAY['Those with sleep concerns','Active individuals with muscle tension','People with stress-related needs','Those with dietary gaps','Anyone experiencing muscle cramps','Those seeking cardiovascular support'],
  timing_tips = ARRAY['Evening dosing may support sleep','Can split into AM/PM doses','Take with food to minimize GI effects','Glycinate and threonate are particularly well-suited for evening use'],
  quality_markers = ARRAY['chelated forms','elemental magnesium amount','no magnesium stearate excess','third-party tested'],
  safety_considerations = ARRAY['Generally very safe at recommended doses','High doses of citrate or oxide may cause loose stools—reduce dose if this occurs','Those with kidney disease should consult healthcare provider before supplementing','May interact with certain medications including antibiotics and bisphosphonates'],
  what_to_expect_summary = ARRAY['Muscle relaxation and reduced cramping are often noticed within the first 1-2 weeks','Sleep quality improvements typically develop over 2-4 weeks of consistent evening supplementation','Those with greater baseline deficiency often experience more noticeable benefits','The calming effects of glycinate form may be noticed relatively quickly'],
  typical_dosage_min = 200,
  typical_dosage_max = 400,
  typical_dosage_unit = 'mg',
  form_notes = '{"glycinate":"Highly absorbable, calming, gentle on stomach","citrate":"Good absorption, may have mild laxative effect","oxide":"Higher elemental content, lower absorption","threonate":"Crosses blood-brain barrier, cognitive focus","malate":"Good for energy and muscle support"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Sleep Quality","timeframe":"2-4 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Muscle Relaxation","timeframe":"1-2 weeks","intensity":"Low to Moderate"}}'::jsonb,
  synergy_notes = 'Magnesium works synergistically with vitamin B6, which aids its cellular uptake—many formulas include both. For sleep support, magnesium pairs well with other calming nutrients like L-theanine, GABA, or melatonin. For bone health, magnesium complements calcium and vitamin D. Athletes often combine magnesium with zinc and B vitamins for comprehensive mineral support.'
WHERE slug = 'magnesium';

-- ===== Multivitamin (multivitamin) =====
UPDATE api.supplements SET
  quick_overview = 'A convenient way to help fill nutritional gaps in the diet. Quality varies significantly between products - look for bioavailable forms and appropriate dosages.',
  extended_overview = 'Multivitamins represent the most commonly consumed dietary supplement category, designed to provide a broad spectrum of essential vitamins and minerals in a single convenient product. The rationale for multivitamin use centers on nutritional insurance—helping to fill gaps that may exist in even well-planned diets due to soil depletion, food processing, individual absorption differences, and the practical challenges of eating optimally every day. However, the multivitamin category encompasses enormous variation in quality, with products ranging from poorly formulated options using cheap, poorly absorbed nutrient forms to sophisticated formulations using bioavailable forms tailored to specific populations. Key quality differentiators include the use of methylated B vitamins (methylfolate and methylcobalamin) rather than synthetic folic acid and cyanocobalamin, chelated minerals for better absorption, appropriate dosages based on actual nutritional science rather than arbitrary percentages, and the exclusion of unnecessary fillers and additives. The best multivitamins are designed with specific populations in mind—men''s and women''s formulas differ in iron content, prenatal vitamins emphasize folate and DHA, and senior formulas may include higher B12 and vitamin D.',
  science_snapshot = 'Research on multivitamins shows mixed results, largely because studies often group vastly different products together. Evidence most consistently supports benefits for those with documented nutritional gaps, restricted diets, or increased needs (pregnancy, aging, certain health conditions). Studies suggest multivitamins may support immune function, energy levels, and cognitive performance, particularly in those with suboptimal baseline nutrition. The importance of bioavailable forms is supported by research showing significant absorption differences—for example, methylfolate is utilized more effectively than folic acid, especially in those with common MTHFR gene variants affecting folate metabolism.',
  key_benefits = ARRAY['Helps fill dietary gaps','Convenient all-in-one formula','Supports overall wellness','Insurance against deficiencies','May support energy levels','Supports immune function'],
  ideal_for = ARRAY['Those with inconsistent diets','People with restricted diets','Older adults with absorption concerns','Those seeking nutritional insurance','Individuals with increased nutrient needs','Those who don''t eat a wide variety of foods'],
  timing_tips = ARRAY['Take with food for better absorption','Morning dosing supports energy nutrients','Split doses if taking multiple servings','Fat-soluble vitamins (A, D, E, K) absorb better with dietary fat'],
  quality_markers = ARRAY['methylated B vitamins','chelated minerals','no synthetic fillers','third-party tested','appropriate dosages (not mega-doses)'],
  safety_considerations = ARRAY['More is not better—avoid products with excessive doses of any nutrient','Men and post-menopausal women should generally choose iron-free formulas','Check for overlap if taking other supplements to avoid exceeding upper limits','Consult healthcare provider if pregnant, nursing, or on medications'],
  what_to_expect_summary = ARRAY['Benefits are often subtle and cumulative rather than immediately noticeable','Those with greater baseline nutritional gaps typically experience more noticeable improvements','Energy support from B vitamins may be noticed within 2-4 weeks if previously deficient','The primary value is long-term nutritional insurance rather than acute effects'],
  typical_dosage_min = 1,
  typical_dosage_max = 3,
  typical_dosage_unit = 'serving',
  form_notes = '{"capsule":"Often contains better forms, easier to swallow","tablet":"Compact, stable shelf life","gummy":"Easier compliance, may have fewer nutrients","liquid":"Good for absorption issues, customizable"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Nutritional Support","timeframe":"4-8 weeks","intensity":"Low to Moderate"},"secondaryOutcome":{"label":"Energy Support","timeframe":"2-4 weeks","intensity":"Low to Moderate"}}'::jsonb,
  synergy_notes = 'A quality multivitamin provides a foundation that may reduce the need for multiple individual supplements. However, certain nutrients like omega-3s, vitamin D (in higher doses), magnesium, and probiotics are often under-represented in multivitamins and may warrant separate supplementation based on individual needs.'
WHERE slug = 'multivitamin';

-- ===== Omega-3 (omega-3) =====
UPDATE api.supplements SET
  quick_overview = 'Essential fatty acids (EPA and DHA) that support cardiovascular, brain, and inflammatory health. Most people benefit from supplementation due to low fish intake.',
  extended_overview = 'Omega-3 fatty acids are essential polyunsaturated fats that the human body cannot produce and must obtain from diet or supplementation. The two most important omega-3s for human health are EPA (eicosapentaenoic acid) and DHA (docosahexaenoic acid), found primarily in fatty fish like salmon, mackerel, sardines, and anchovies. While the plant-based omega-3 ALA (alpha-linolenic acid) from sources like flaxseed can be converted to EPA and DHA, this conversion is extremely inefficient (typically less than 5%), making direct EPA/DHA intake important. These fatty acids are incorporated into cell membranes throughout the body, where they influence membrane fluidity and serve as precursors to signaling molecules called resolvins and protectins that help regulate inflammatory processes. DHA is particularly concentrated in the brain and retina, supporting cognitive function and vision, while EPA appears particularly important for cardiovascular health and mood regulation. Given that most Western diets are dramatically skewed toward omega-6 fatty acids (with ratios often exceeding 15:1 instead of the ideal 4:1 or lower), omega-3 supplementation can help restore balance and support optimal inflammatory status.',
  science_snapshot = 'Omega-3 research represents one of the most robust bodies of evidence in nutritional science. Meta-analyses demonstrate significant benefits for cardiovascular markers including triglyceride reduction (typically 15-30% at therapeutic doses), modest blood pressure improvements, and reduced risk of cardiac events. Research supports cognitive benefits, particularly for brain development and potentially for age-related cognitive decline. Studies on inflammation show omega-3s can reduce inflammatory markers like C-reactive protein. The evidence for mood support, particularly EPA-dominant formulas for depression, has grown substantially. Quality markers like IFOS certification and low oxidation levels are important, as rancid fish oil may be counterproductive.',
  key_benefits = ARRAY['Supports heart health','Brain and cognitive support','Healthy inflammatory response','Eye and vision support','May support mood balance','Supports healthy triglyceride levels'],
  ideal_for = ARRAY['Those not eating fatty fish regularly','People seeking cardiovascular support','Those wanting cognitive support','Active individuals for recovery','Anyone with inflammatory concerns','Those seeking mood support'],
  timing_tips = ARRAY['Take with meals containing fat','Split high doses between meals','Refrigeration may reduce fishy taste','Taking with largest meal of the day optimizes absorption'],
  quality_markers = ARRAY['IFOS certified','low oxidation','EPA+DHA content','molecularly distilled','tested for heavy metals and PCBs'],
  safety_considerations = ARRAY['Generally very safe; may cause fishy burps or mild GI effects in some','High doses (>3g EPA+DHA) may affect bleeding time—discuss with healthcare provider if on blood thinners','Choose products tested for mercury, PCBs, and other contaminants','Avoid if allergic to fish (algae-based alternatives available)'],
  what_to_expect_summary = ARRAY['Triglyceride improvements are typically measurable after 8-12 weeks of consistent supplementation','Anti-inflammatory effects may be noticed through improved joint comfort or recovery within 6-8 weeks','Cognitive and mood benefits often require longer-term supplementation (3+ months) to become apparent','The Omega-3 Index blood test can measure your omega-3 status and track improvement over time'],
  typical_dosage_min = 1000,
  typical_dosage_max = 3000,
  typical_dosage_unit = 'mg',
  form_notes = '{"triglyceride":"Natural form, good absorption","ethyl ester":"Concentrated, take with fatty meal","phospholipid":"Krill-derived, includes astaxanthin","algae":"Plant-based DHA/EPA source"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Cardiovascular Markers","timeframe":"8-12 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Inflammatory Balance","timeframe":"6-8 weeks","intensity":"Low to Moderate"}}'::jsonb,
  synergy_notes = 'Omega-3s complement vitamin D supplementation, as both are often deficient and work together for immune and cardiovascular health. For inflammatory support, omega-3s pair well with curcumin. CoQ10 is another popular combination for comprehensive cardiovascular support. Phospholipid forms (krill oil) include astaxanthin, adding antioxidant benefits.'
WHERE slug = 'omega-3';

-- ===== Prebiotics (prebiotics) =====
UPDATE api.supplements SET
  quick_overview = 'Non-digestible fibers that feed beneficial gut bacteria. Prebiotics support a healthy microbiome, which influences digestion, immunity, and overall health.',
  extended_overview = 'Prebiotics are specialized plant fibers that act as food for beneficial bacteria in the gut, selectively stimulating the growth and activity of health-promoting microorganisms in the colon. Unlike probiotics, which are live bacteria, prebiotics are non-living dietary components that resist digestion in the upper gastrointestinal tract and arrive intact in the colon, where they are fermented by beneficial bacteria. This fermentation process produces short-chain fatty acids (SCFAs) like butyrate, propionate, and acetate, which serve as fuel for colon cells, help maintain gut barrier integrity, and exert systemic effects on metabolism and immune function. The most well-researched prebiotics include inulin (found naturally in chicory root, Jerusalem artichoke, and onions), fructooligosaccharides (FOS), galactooligosaccharides (GOS), and resistant starch. The concept of prebiotics emerged from the recognition that gut bacteria play a crucial role in human health, and that we can positively influence the microbiome composition not only by adding beneficial bacteria (probiotics) but also by feeding the beneficial bacteria already present. Modern diets often lack sufficient prebiotic fiber, as processed foods typically have reduced fiber content, making supplementation an attractive option for supporting gut health.',
  science_snapshot = 'Research demonstrates that prebiotic supplementation can significantly alter gut microbiome composition, typically increasing beneficial Bifidobacteria and Lactobacilli populations while reducing potentially harmful bacteria. Clinical studies show prebiotics can improve bowel regularity, enhance mineral absorption (particularly calcium and magnesium), support immune function, and may even influence appetite regulation and metabolic health. The production of short-chain fatty acids, particularly butyrate, is associated with reduced inflammation in the gut and improved intestinal barrier function. Studies suggest synbiotic combinations (prebiotics plus probiotics) may offer enhanced benefits compared to either alone. Importantly, research indicates that gradual dose introduction is key to minimizing digestive discomfort as the gut microbiome adapts.',
  key_benefits = ARRAY['Feeds beneficial gut bacteria','Supports digestive health','May enhance immune function','Promotes regularity','Supports short-chain fatty acid production','May enhance mineral absorption'],
  ideal_for = ARRAY['Those working on gut health','People taking probiotics','Those with low fiber intake','Anyone seeking digestive support','Those wanting to support their existing beneficial bacteria','Individuals interested in metabolic health'],
  timing_tips = ARRAY['Start with low doses and increase gradually','Can be taken any time of day','Combine with probiotics for synbiotic effect','Taking with meals may reduce initial digestive adjustment symptoms'],
  quality_markers = ARRAY['specific fiber type listed','gradual dosing guidelines','no added sugars','research-backed sources'],
  safety_considerations = ARRAY['Start with low doses to minimize gas and bloating during gut adaptation period','Those with IBS or FODMAP sensitivities should introduce cautiously as some prebiotics are high-FODMAP','Generally very safe, but high doses may cause digestive discomfort','Stay well-hydrated when increasing fiber intake'],
  what_to_expect_summary = ARRAY['Initial adjustment may include temporary bloating or gas as gut bacteria adapt—this typically resolves within 1-2 weeks','Improved regularity and bowel comfort often noticed within 2-4 weeks of consistent use','Starting with a low dose and gradually increasing over 1-2 weeks helps minimize initial digestive discomfort','Benefits compound over time as beneficial bacterial populations grow and stabilize'],
  typical_dosage_min = 3000,
  typical_dosage_max = 10000,
  typical_dosage_unit = 'mg',
  form_notes = '{"inulin":"Versatile fiber, gentle introduction needed","fos":"Fructooligosaccharides, well-researched","gos":"Galactooligosaccharides, similar to breast milk","powder":"Easy to add to foods and drinks"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Digestive Comfort","timeframe":"2-4 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Regularity Improvement","timeframe":"1-2 weeks","intensity":"Moderate"}}'::jsonb,
  synergy_notes = 'Prebiotics and probiotics together form a synbiotic combination that may be more effective than either alone. Prebiotics help the probiotic bacteria survive and thrive in the gut. They also complement digestive enzymes and can be paired with fiber supplements for comprehensive digestive support. For those focused on gut healing, prebiotics work well alongside L-glutamine and other gut-supportive nutrients.'
WHERE slug = 'prebiotics';

-- ===== Probiotics (probiotics) =====
UPDATE api.supplements SET
  quick_overview = 'Live beneficial bacteria that support gut health and immune function. Strain specificity matters - different strains have different researched benefits.',
  extended_overview = 'Probiotics are live microorganisms that, when administered in adequate amounts, confer health benefits to the host. The human gut contains trillions of bacteria—collectively known as the gut microbiome—that play crucial roles in digestion, nutrient synthesis, immune function, and even brain health through the gut-brain axis. Probiotic supplementation aims to introduce or reinforce beneficial bacterial populations, helping maintain a healthy microbial balance. The most commonly supplemented probiotics belong to the Lactobacillus and Bifidobacterium genera, though other species like Saccharomyces boulardii (a beneficial yeast) and soil-based organisms are also used. A critical concept in probiotic science is strain specificity—benefits documented for one strain cannot be assumed to apply to another, even within the same species. For example, Lactobacillus rhamnosus GG has been extensively studied for immune and digestive benefits, while other L. rhamnosus strains may have different effects. This is why quality probiotic products specify exact strains (genus, species, and strain designation) rather than just listing species. CFU (colony-forming units) count indicates the number of viable bacteria, though more isn''t always better—appropriate dosing varies by strain and intended use.',
  science_snapshot = 'Clinical research on probiotics spans diverse applications with varying levels of evidence. Strong evidence supports probiotic use for antibiotic-associated diarrhea prevention, with specific strains like S. boulardii and L. rhamnosus GG showing significant protective effects. Studies demonstrate benefits for irritable bowel syndrome symptoms with multi-strain formulas, and emerging research explores applications in immune modulation, mood support (through the gut-brain axis), and metabolic health. The importance of strain specificity is increasingly recognized—clinical benefits are tied to specific strains, not just species. Research also emphasizes that probiotics work differently than colonizing bacteria; most pass through the gut, exerting benefits during transit rather than permanently altering microbiome composition, which is why consistent supplementation is often needed for sustained effects.',
  key_benefits = ARRAY['Supports healthy gut flora','May enhance immune response','Digestive comfort support','Strain-specific benefits available','Supports gut-brain axis communication','May help restore balance after antibiotic use'],
  ideal_for = ARRAY['Those after antibiotic use','People with digestive concerns','Those seeking immune support','Anyone wanting gut health maintenance','Travelers concerned about digestive disruption','Those interested in gut-brain axis support'],
  timing_tips = ARRAY['Many strains best on empty stomach','Some can be taken with meals','Consistency is important for ongoing benefits','When using with antibiotics, take at least 2 hours apart'],
  quality_markers = ARRAY['specific strains listed','CFU at expiration','survivability tested','clinical strains'],
  safety_considerations = ARRAY['Generally very safe for most people, including long-term use','Those with compromised immune systems should consult healthcare provider before use','May cause temporary gas or bloating during initial adaptation period','Quality matters—choose products with verified potency through expiration date'],
  what_to_expect_summary = ARRAY['Some users notice digestive improvements within the first 1-2 weeks, though 2-4 weeks is typical for meaningful changes','Initial adjustment may include temporary changes in digestion as the gut microbiome adapts','Immune support benefits typically develop over 4-8 weeks of consistent use','Benefits often depend on choosing strains matched to your specific health goals—consult product research or healthcare provider'],
  typical_dosage_min = 1,
  typical_dosage_max = 100,
  typical_dosage_unit = 'billion CFU',
  form_notes = '{"capsule":"Protected delivery, shelf-stable options","powder":"Higher doses possible, mix into foods","refrigerated":"May contain more viable organisms","shelf-stable":"Convenient, tested for stability"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Digestive Balance","timeframe":"2-4 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Immune Support","timeframe":"4-8 weeks","intensity":"Low to Moderate"}}'::jsonb,
  synergy_notes = 'Probiotics work synergistically with prebiotics (together called synbiotics), as prebiotics provide fuel for beneficial bacteria to thrive. Digestive enzymes can complement probiotics for comprehensive digestive support. For those recovering from antibiotic use, combining strain-specific probiotics with gut-healing nutrients like L-glutamine may accelerate recovery. Some formulations include postbiotics (beneficial compounds produced by probiotics) for additional support.'
WHERE slug = 'probiotics';

-- ===== Sulforaphane (sulforaphane) =====
UPDATE api.supplements SET
  quick_overview = 'A compound from cruciferous vegetables with potent cellular protective properties. Activates Nrf2 pathways involved in antioxidant defense and detoxification.',
  extended_overview = 'Sulforaphane is a powerful bioactive compound found in cruciferous vegetables, with the highest concentrations occurring in broccoli sprouts—containing 20-100 times more than mature broccoli. This remarkable compound is not actually present in the vegetables themselves but is formed when glucoraphanin (a precursor compound) comes into contact with myrosinase (an enzyme) during chewing, chopping, or digestion. Sulforaphane has garnered significant scientific attention for its ability to activate the Nrf2 pathway, often called the ''master regulator'' of cellular antioxidant response. When Nrf2 is activated, it travels to the cell nucleus and triggers the production of over 200 protective genes involved in antioxidant defense, detoxification of harmful compounds, and cellular repair mechanisms. This makes sulforaphane fundamentally different from direct antioxidants like vitamin C—rather than neutralizing free radicals itself, it upregulates the body''s own antioxidant production systems. The compound also supports Phase II detoxification enzymes in the liver, helping the body process and eliminate potentially harmful substances. Research interest in sulforaphane spans areas including cellular protection, brain health, metabolic function, and healthy aging.',
  science_snapshot = 'Research on sulforaphane has demonstrated its potent ability to activate Nrf2-dependent antioxidant pathways, with effects lasting 24-72 hours after a single dose due to its mechanism of inducing gene expression rather than direct antioxidant activity. Clinical and preclinical studies have explored applications in supporting cellular health, cognitive function, and metabolic balance. Studies show sulforaphane can cross the blood-brain barrier, leading to research on its neuroprotective potential. The bioavailability of sulforaphane is significantly enhanced when supplements include myrosinase enzyme or when consumed with mustard seed powder (which contains myrosinase). Research confirms that glucoraphanin supplements without myrosinase have dramatically reduced conversion to active sulforaphane, making formulation a critical quality consideration.',
  key_benefits = ARRAY['Activates cellular defense pathways','Supports detoxification processes','Potent antioxidant support','Derived from broccoli compounds','Supports Nrf2 master antioxidant pathway','May support brain and cognitive health'],
  ideal_for = ARRAY['Those seeking cellular protection','People interested in longevity support','Those not eating cruciferous vegetables','Health optimization enthusiasts','Those interested in Nrf2 pathway activation','Individuals focused on detoxification support'],
  timing_tips = ARRAY['Take with food for comfort','Morning dosing aligns with circadian patterns','Consistent daily use recommended','If using glucoraphanin form, consider adding mustard seed powder for myrosinase'],
  quality_markers = ARRAY['standardized sulforaphane','myrosinase included','fresh broccoli source','stabilization method'],
  safety_considerations = ARRAY['Generally well-tolerated at recommended doses','May cause mild digestive discomfort in some individuals, especially at higher doses','Those with thyroid conditions should consult healthcare provider, as cruciferous compounds may affect thyroid function in sensitive individuals','Pregnant or nursing women should consult healthcare provider before supplementing'],
  what_to_expect_summary = ARRAY['Nrf2 pathway activation begins within hours of consumption, with effects lasting 24-72 hours','Cumulative benefits from consistent supplementation typically become noticeable over 2-4 weeks','Effects are primarily cellular and may not produce obvious subjective feelings','Those using bioavailable forms (with myrosinase or stabilized sulforaphane) experience more consistent benefits'],
  typical_dosage_min = 10,
  typical_dosage_max = 50,
  typical_dosage_unit = 'mg',
  form_notes = '{"with myrosinase":"Enzyme needed for conversion, more effective","stabilized":"Pre-formed sulforaphane","broccoli sprout":"Natural source, variable content","glucoraphanin":"Precursor form, needs enzyme activation"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Cellular Defense Activation","timeframe":"2-4 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Detoxification Support","timeframe":"4-8 weeks","intensity":"Low to Moderate"}}'::jsonb,
  synergy_notes = 'Sulforaphane''s effects on Nrf2 activation can be complemented by other pathway activators like curcumin and green tea catechins. For comprehensive cellular protection, it pairs well with direct antioxidants like vitamin C and E, which work through different mechanisms. Some longevity-focused protocols combine sulforaphane with other compounds being researched for healthy aging, such as resveratrol or NMN. When using glucoraphanin-based supplements, consuming with mustard seed powder provides the myrosinase enzyme needed for conversion.'
WHERE slug = 'sulforaphane';

-- ===== Vitamin C (vitamin-c) =====
UPDATE api.supplements SET
  quick_overview = 'An essential water-soluble vitamin with antioxidant properties. Supports immune function, collagen synthesis, and iron absorption. Regular intake preferred over mega-doses.',
  extended_overview = 'Vitamin C, also known as ascorbic acid, is an essential water-soluble vitamin that humans cannot synthesize and must obtain through diet or supplementation. Unlike most mammals, humans lack the enzyme (L-gulonolactone oxidase) needed to produce vitamin C internally, making dietary intake critical. This versatile nutrient serves numerous functions throughout the body: it acts as a powerful antioxidant, neutralizing free radicals and protecting cells from oxidative damage; it serves as an essential cofactor for collagen synthesis, making it crucial for skin, connective tissue, and wound healing; it enhances immune function through multiple mechanisms including supporting the activity of white blood cells; and it dramatically improves the absorption of non-heme iron from plant foods. Vitamin C is rapidly absorbed in the small intestine, but absorption efficiency decreases as dose increases—the body absorbs approximately 70-90% of moderate doses (30-180mg) but less than 50% of doses exceeding 1,000mg. This pharmacokinetic reality, combined with vitamin C''s water-solubility and rapid excretion, supports the practice of taking divided doses throughout the day rather than single mega-doses. Various forms exist including standard ascorbic acid, buffered forms for those with sensitive stomachs, and liposomal formulations designed for enhanced absorption.',
  science_snapshot = 'Research consistently supports vitamin C''s essential roles in immune function, collagen synthesis, and antioxidant defense. Meta-analyses show that regular vitamin C supplementation can reduce the duration and severity of common colds, though it doesn''t appear to prevent colds in the general population (it may help prevent colds in those under physical stress like athletes or soldiers). Studies demonstrate vitamin C''s critical role in wound healing and skin health through its involvement in collagen production. The relationship between vitamin C and iron absorption is well-established, with vitamin C increasing non-heme iron absorption by 2-3 fold when consumed together. Liposomal vitamin C has shown enhanced bioavailability in some studies, potentially achieving higher blood levels than standard ascorbic acid at equivalent doses.',
  key_benefits = ARRAY['Supports immune function','Essential for collagen production','Antioxidant protection','Enhances iron absorption','Supports wound healing and tissue repair','May support skin health and appearance'],
  ideal_for = ARRAY['Those seeking immune support','People under physical stress','Smokers (higher needs)','Those wanting antioxidant support','Those with low fruit and vegetable intake','Anyone taking iron supplements (enhances absorption)'],
  timing_tips = ARRAY['Split doses throughout the day','Take with meals if sensitive to acidity','Consistent daily intake preferred','Take with iron supplements to enhance iron absorption'],
  quality_markers = ARRAY['form specified','bioflavonoids included','no artificial colors','appropriate dose'],
  safety_considerations = ARRAY['Generally very safe, even at higher doses','High doses (>2,000mg/day) may cause digestive upset, diarrhea in some individuals','Those with kidney disease or history of kidney stones should consult healthcare provider before high-dose supplementation','Vitamin C may affect certain lab tests—inform healthcare provider of supplementation'],
  what_to_expect_summary = ARRAY['Immune support benefits develop over 2-4 weeks of consistent daily supplementation','Those with previously low intake may notice improvements in energy and recovery','Skin and collagen-related benefits typically require longer-term supplementation (8+ weeks)','Splitting doses throughout the day provides more consistent blood levels than single large doses'],
  typical_dosage_min = 250,
  typical_dosage_max = 2000,
  typical_dosage_unit = 'mg',
  form_notes = '{"ascorbic acid":"Pure form, may be acidic for some","buffered":"Gentle on stomach, mineral ascorbates","liposomal":"Enhanced absorption technology","ester-c":"pH neutral, contains metabolites"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Immune Support","timeframe":"2-4 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Antioxidant Status","timeframe":"4-8 weeks","intensity":"Low to Moderate"}}'::jsonb,
  synergy_notes = 'Vitamin C works synergistically with vitamin E, regenerating vitamin E after it neutralizes free radicals—together they provide more comprehensive antioxidant protection. It dramatically enhances iron absorption and is often recommended alongside iron supplements. For collagen support, vitamin C pairs well with collagen peptides. Bioflavonoids (often included in vitamin C supplements) may enhance vitamin C absorption and provide additional antioxidant benefits. For immune support, vitamin C complements zinc and elderberry.'
WHERE slug = 'vitamin-c';

-- ===== Vitamin D (vitamin-d) =====
UPDATE api.supplements SET
  quick_overview = 'The "sunshine vitamin" essential for bone health, immune function, and numerous bodily processes. Deficiency is common, especially in northern latitudes and indoor lifestyles.',
  extended_overview = 'Vitamin D is unique among vitamins because it functions more like a hormone than a traditional vitamin, with receptors found in virtually every cell type in the human body. While classified as a vitamin, humans can synthesize vitamin D when UVB radiation from sunlight strikes the skin and triggers a conversion process involving cholesterol. However, modern lifestyles characterized by indoor work, sunscreen use, and living at higher latitudes have made vitamin D deficiency remarkably common—estimates suggest that up to 40% of adults in the United States and even higher percentages in northern countries have insufficient levels. Vitamin D plays critical roles in calcium absorption and bone metabolism, explaining its well-established importance for skeletal health. Beyond bones, vitamin D receptors in immune cells, brain tissue, muscles, and the cardiovascular system hint at the vitamin''s far-reaching influence. Vitamin D3 (cholecalciferol) is the form produced in human skin and found in animal sources, while D2 (ergocalciferol) comes from plant and fungal sources. Research consistently shows D3 is more effective at raising and maintaining blood levels, making it the preferred supplemental form. Blood testing (25-hydroxyvitamin D) is the gold standard for assessing status and optimizing supplementation.',
  science_snapshot = 'Research on vitamin D has expanded dramatically, with studies exploring applications far beyond bone health. Strong evidence supports vitamin D''s role in calcium absorption and bone mineral density maintenance. Meta-analyses demonstrate associations between adequate vitamin D status and reduced risk of respiratory infections, with some studies showing supplementation benefits for those with low baseline levels. Research on vitamin D and mood shows correlations between deficiency and depression, though intervention studies show mixed results. Studies on muscle function support vitamin D''s role in muscle strength and fall prevention in older adults. The optimal blood level remains debated, but most experts suggest 30-50 ng/mL (75-125 nmol/L) as a reasonable target, with individual needs varying based on genetics, health status, and other factors.',
  key_benefits = ARRAY['Supports bone health','Immune system modulation','Mood and wellbeing support','Muscle function support','Supports calcium absorption','May support cardiovascular health'],
  ideal_for = ARRAY['Those with limited sun exposure','People in northern climates','Older adults','Those with darker skin','Office workers and those with indoor lifestyles','Those with tested deficiency or insufficiency'],
  timing_tips = ARRAY['Take with meals containing fat','Morning or midday mimics natural production','Test levels to optimize dosing','Consistent daily dosing more effective than sporadic high doses'],
  quality_markers = ARRAY['D3 form','oil-based for absorption','third-party tested','appropriate IU per serving'],
  safety_considerations = ARRAY['Safe at recommended doses; toxicity rare but possible with very high doses over extended periods','Those with granulomatous diseases, some lymphomas, or hypercalcemia should consult healthcare provider','Blood testing recommended to avoid over-supplementation, especially at doses >4,000 IU daily','Upper limit generally considered 4,000 IU/day, though some individuals may safely take more under medical supervision'],
  what_to_expect_summary = ARRAY['Blood levels typically rise measurably within 4-8 weeks, reaching new steady state around 8-12 weeks','Those with severe deficiency may notice improvements in energy and mood as levels normalize','Immune and bone health benefits are often subtle and cumulative rather than immediately noticeable','Blood testing before and after 3 months helps confirm appropriate dosing for your individual needs'],
  typical_dosage_min = 1000,
  typical_dosage_max = 5000,
  typical_dosage_unit = 'IU',
  form_notes = '{"d3":"Cholecalciferol, more effective than D2","d2":"Ergocalciferol, plant-derived","with k2":"Synergistic for calcium metabolism","liquid":"Easy dosing adjustment, good absorption"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Vitamin D Level Increase","timeframe":"8-12 weeks","intensity":"Moderate to High"},"secondaryOutcome":{"label":"Immune Function","timeframe":"4-8 weeks","intensity":"Low to Moderate"}}'::jsonb,
  synergy_notes = 'Vitamin D works synergistically with vitamin K2, which helps direct calcium to bones rather than arteries—many experts recommend combining the two. Magnesium is required for vitamin D metabolism, and deficiency may impair vitamin D function. For bone health, vitamin D pairs with calcium to enhance absorption. Omega-3 fatty acids complement vitamin D for immune and cardiovascular support. Taking vitamin D with a meal containing fat significantly improves absorption.'
WHERE slug = 'vitamin-d';

-- ===== Whey Protein (whey-protein) =====
UPDATE api.supplements SET
  quick_overview = 'A fast-digesting complete protein derived from milk. Rich in branched-chain amino acids, particularly leucine, which supports muscle protein synthesis.',
  extended_overview = 'Whey protein is derived from milk during the cheese-making process, representing approximately 20% of milk''s total protein content (with casein making up the remaining 80%). What makes whey exceptional among protein sources is its rapid digestion and absorption kinetics, complete essential amino acid profile, and particularly high concentration of leucine—the amino acid that serves as the primary trigger for muscle protein synthesis. When consumed, whey protein is digested quickly, causing a rapid and pronounced rise in blood amino acid levels that peaks within 60-90 minutes. This ''fast'' profile makes whey ideal for post-workout consumption when muscles are primed for protein synthesis. Whey exists in several forms: concentrate (70-80% protein with some lactose and fat), isolate (90%+ protein with minimal lactose, ideal for those with lactose sensitivity), and hydrolysate (pre-digested for even faster absorption, though often more expensive and with a bitter taste). Beyond muscle building, whey protein has been studied for its potential benefits in satiety and weight management, immune support through immunoglobulins and lactoferrin, and even blood pressure regulation. For most people, whey concentrate offers the best value, while isolate is preferred by those with lactose concerns or seeking maximum protein per calorie.',
  science_snapshot = 'Research consistently demonstrates whey protein''s effectiveness for supporting muscle protein synthesis, with studies showing superior acute anabolic response compared to other protein sources like soy or casein. Meta-analyses confirm that whey protein supplementation, combined with resistance training, enhances gains in muscle mass and strength. The high leucine content (approximately 10-11% of total protein) is believed to be a key factor, as leucine directly activates the mTOR pathway that initiates muscle building. Studies also show whey can support satiety and may help preserve lean mass during weight loss diets. Research on whey''s bioactive components suggests potential benefits for immune function and blood pressure, though these applications require further investigation. Importantly, studies confirm no adverse effects on kidney or liver function in healthy individuals consuming protein within normal ranges.',
  key_benefits = ARRAY['Supports muscle growth and repair','Fast-absorbing protein source','High in leucine (muscle trigger)','Complete amino acid profile','Convenient way to meet protein goals','May support satiety and weight management'],
  ideal_for = ARRAY['Athletes and active individuals','Those doing resistance training','People needing convenient protein','Post-workout recovery support','Those struggling to meet protein goals through food alone','Older adults seeking to maintain muscle mass'],
  timing_tips = ARRAY['Post-workout window is popular','Can be used any time protein is needed','Morning use supports daily protein goals','Spreading protein intake throughout the day optimizes muscle protein synthesis'],
  quality_markers = ARRAY['protein per serving','amino acid profile','third-party tested','low heavy metals'],
  safety_considerations = ARRAY['Not suitable for those with milk protein allergies','Those with lactose intolerance should choose isolate or lactose-free formulations','High-quality products are tested for heavy metals and contaminants','No evidence of kidney or liver harm in healthy individuals at normal intakes'],
  what_to_expect_summary = ARRAY['Improved recovery from workouts is often noticed within the first 1-2 weeks of consistent post-workout use','Strength and muscle gains become more apparent after 4-8 weeks when combined with resistance training','Those previously under-consuming protein may notice more significant benefits','Whey is a tool to help meet protein goals—results depend on overall diet, training, and consistency'],
  typical_dosage_min = 20000,
  typical_dosage_max = 50000,
  typical_dosage_unit = 'mg',
  form_notes = '{"concentrate":"70-80% protein, contains some lactose","isolate":"90%+ protein, minimal lactose","hydrolysate":"Pre-digested, fastest absorption","native":"From milk, not cheese byproduct"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Muscle Recovery","timeframe":"1-2 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Strength Progress","timeframe":"4-8 weeks","intensity":"Moderate"}}'::jsonb,
  synergy_notes = 'Whey protein pairs well with creatine for comprehensive muscle-building support—both are among the most researched and effective sports supplements. For around-the-clock protein delivery, combining whey (fast) with casein (slow) provides both immediate post-workout amino acids and sustained overnight release. Carbohydrates consumed with whey post-workout may enhance muscle glycogen replenishment. For those focused on body composition, whey can be combined with caffeine or green tea extract as part of a comprehensive approach.'
WHERE slug = 'whey-protein';

-- ===== Zinc (zinc) =====
UPDATE api.supplements SET
  quick_overview = 'An essential trace mineral supporting immune function, wound healing, and numerous enzymatic processes. Many adults have marginal zinc status.',
  key_benefits = ARRAY['Supports immune function','Important for wound healing','Supports skin health','Essential for enzyme function'],
  ideal_for = ARRAY['Those seeking immune support','Vegetarians (lower absorption from plants)','Athletes (increased losses)','Those with skin concerns'],
  timing_tips = ARRAY['Take with food to prevent nausea','Avoid taking with calcium or iron','Lozenges for acute throat support'],
  quality_markers = ARRAY['form specified','elemental zinc amount','copper balance considered','third-party tested'],
  typical_dosage_min = 15,
  typical_dosage_max = 50,
  typical_dosage_unit = 'mg',
  form_notes = '{"picolinate":"Well-absorbed form","citrate":"Good absorption, common form","gluconate":"Gentle, often in lozenges","bisglycinate":"Chelated, gentle on stomach"}'::jsonb,
  what_to_expect = '{"primaryOutcome":{"label":"Immune Support","timeframe":"4-8 weeks","intensity":"Moderate"},"secondaryOutcome":{"label":"Zinc Status Improvement","timeframe":"8-12 weeks","intensity":"Moderate"}}'::jsonb
WHERE slug = 'zinc';

COMMIT;

-- Migration complete: 18 supplements updated